CREATE TABLE IF NOT EXISTS `log` (
  `id`   INT(11)  NOT NULL AUTO_INCREMENT,
  `date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `type` VARCHAR(255),
  `key1` VARCHAR(255),
  `key2` VARCHAR(255),
  PRIMARY KEY (`id`)
)
  ENGINE = InnoDB
  DEFAULT CHARSET = utf8;
